# See `verl/trainer/config/config.py:RewardManagerConfig` for more details.
_target_: verl.trainer.config.config.RewardManagerConfig
source: register
name: agent_loop
module:
  _target_: verl.trainer.config.config.ModuleConfig
  path: null
  name: custom_reward_manager
